# Generated by Django 5.1 on 2024-08-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('AP', 'Apartment'), ('VI', 'Villa'), ('HO', 'House'), ('ST', 'Studio')], default='HO', max_length=2),
        ),
    ]
